### ISSUE TITLE
new lines on unix vs windows

### ISSUE THREAD

**Issue by joseph-jja** [vkadam/grunt-jsbeautifier#27]
We have both windows and mac/linux developers. The new line on mac is different than windows and this is causing issues at each run.  It shows every developer that all the files have been beautified when the difference is only the new line characters.  Is there any way to standardize the output of this plugin to generate the same new line characters for windows and mac?

**Comment by tongc** [comment]
@joseph-jja it would be much appreciated if you can share specifically where you added what configurations to stop this annoying line break from happening again?
thanks

**Comment by joseph-jja** [comment]
I added this to gitattributes
> cat .gitattributes 
* eol=lf

and then in the Gruntfile.js

grunt.util.linefeed = '\n';

**Comment by tongc** [comment]
thanks @joseph-jja
