### ISSUE TITLE
run jsBeautifier on single file

### ISSUE THREAD

**Issue by nsisodiya** [vkadam/grunt-jsbeautifier#39]
I want that whenever my js file got changes I want to run beautifier on that file. I do not want to run on all js file.
I am using "watch" livereload for this purpose. what should I do ??

grunt.registerTask('singleJSBeautifier', "Add git revision number", function(filePath) {
    //Code for running jsBeautifier on single file.????
  });

**Comment by vkadam** [comment]
I think this will fulfill your need, https://github.com/gruntjs/grunt-contrib-watch#compiling-files-as-needed

**Comment by vkadam** [comment]
Anyway, I have added option to grunt-jsbeatifier itself, here https://github.com/vkadam/grunt-jsbeautifier#run-single-file (v 0.2.12)
So you can use either way for beautifying updated files only.
Closing issue now.
