### ISSUE TITLE
JS: End with newline

### ISSUE THREAD

**Issue by claudiojs** [vkadam/grunt-jsbeautifier#45]
Hi! Thanks for writing this task!

I was wondering why I can't use this option:
https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L75

Then I figured it out that the task allways inserts a newline after beautifying a JavaScript file - something that I dont't want to. It is unfortunately impossible to configure it with the parameter options. Could you please change this?

Here is the code that I mean:
https://github.com/vkadam/grunt-jsbeautifier/blob/c0a47d0e902e755e26b0911b9a0e36b1a21a778e/lib/jsbeautifier.js#L62

and here:
https://github.com/vkadam/grunt-jsbeautifier/blob/c0a47d0e902e755e26b0911b9a0e36b1a21a778e/lib/jsbeautifier.js#L86

**Comment by vkadam** [comment]
This was done way before "end_with_newline" options was added to js-beautify, this was the pull request for it https://github.com/vkadam/grunt-jsbeautifier/pull/5. 

There is also a pull request https://github.com/vkadam/grunt-jsbeautifier/pull/46 for fix but test cases are failing. I will get it correct and honor "end_with_newline"

**Comment by vkadam** [comment]
Pushed fix in version 0.2.9
