### ISSUE TITLE
bracestyle expand causing odd formatting with JSON objects

### ISSUE THREAD

**Issue by storey247** [vkadam/grunt-jsbeautifier#47]
I have found a couple of scenarios where using the bracestyle expand when formatting .js code causes a few odd results.

Consider the following:
```javascript
var x = y || {};
```
this seems to result in the following code (which looks a little clumsy):
```javascript
var x = y || 
{};
```

It would be nice if the bracing was left untouched after the logical OR operand in these scenarios

**Comment by vkadam** [comment]
I am not able to reproduce it, I have added a test case to prove it. Take a look at commit 70e5694e17ea84c1013cf555aec7f52ca2e74373.

Also this plugin does not do formatting its own, it just proxy to [js-beautify](https://github.com/beautify-web/js-beautify). If you can still reproduce at your side, send me content of files and version's of plugin you are using. I will be happy to reproduce and help to find out the cause for it
