### ISSUE TITLE
JsBeautifier silently finish all grunt task when no source

### ISSUE THREAD

**Issue by miceno** [vkadam/grunt-jsbeautifier#55]
Hi,

I am running a jsbeautifier task the very first in my grunt file and if there is no source file, the task silently exists and it doesn't continue processing the remaining grunt tasks :(

**Comment by vkadam** [comment]
Added a fix for it under commit e48b8fd264d44136b83bd4221d979beec54d2227, will be released in next version

**Comment by vkadam** [comment]
Release 0.2.12
