### ISSUE TITLE
Only modify file when it is not well-formatted

### ISSUE THREAD

**Issue by mathwo** [vkadam/grunt-jsbeautifier#61]
To be more specific, we hope the formatter can leave those files that are already formatted untouched, and only modify those files that have to be changed.

This is an unobtrusive feature that does no side-effect harm to all users, but it would be a great feature when we use version control system (which is absolutely true). If and only if we have this feature, beautifier can be a routine process in default. Otherwise, we can only run jsbeautifier when we randomly remember it.

**Comment by vkadam** [comment]
I see you have already closed the ticket, and as per you mentioned in email you identified that its not re-visiting well-formatted files. 
Just to be clear on that part, it will revisit well-formatted files, but as there is not change so you won't see them as modified.
But if you are looking for a feature something when you only like to formatted, files modified by you locally while using SCM and the un-formatted files by another committers then its going to need a changes for it plugin.

**Comment by mathwo** [comment]
Yes, after testing and checking the javascript code I found that it's okay since formatted files will not be modified. Since I add it to default task in gulp, this would be an important feature otherwise the diff will be huge. Thanks!
