### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by NoelBroda** [vkadam/grunt-jsbeautifier#62]
Hi all!
I'm working in a project where we are using jsbeautifier.
I really didn't know what jsbeautifier do, so, I come here looking for some kind of documentation to understand what does this library do.

But... There is no place in the whole README where you say what this library do.

Can you let us know what is jsbeautifier?
Thank you.

**Comment by vkadam** [comment]
Beautify js, css, html and json files using Grunt and https://github.com/einars/js-beautify

This is grunt plugin to beatify js, css, html files. Anything which is supported by https://github.com/einars/js-beautify

**Comment by vkadam** [comment]
Is is mentioned on git repo description
